### ISSUE TITLE
docker hub image not working

### ISSUE THREAD

**Issue by MakiG0** [standardnotes/web#467]
I read about standardnotes last week and i think that i could get my notes under control. Many thanks for this great software. 
I want to host standardnotes myself with docker.
I was able to set up the sync server successfully with docker and docker-compose. However, I get the following error message when setting up the web-service:
`starting container process caused "exec: \"./docker/entrypoint.sh\": stat ./docker/entrypoint.sh: no such file or directory": unknown
`

i tried the standardnotes/web:stable version.

Is it possible that the image is not correct or or am I doing something wrong?

**Comment by JaspalSuri** [comment]
I'll assign this issue to one of our back-end devs; they will be able to help you sometime next week. Any other information about your setup would be greatly appreciated! 

Thanks for using the official image from Docker Hub!

**Comment by MakiG0** [comment]
thanks a lot for your response. 
I tried to run the web docker with this docker-compose:
```
version: "3.6"
services:
  standardnotes-web:
    image: standardnotes/web:stable
    container_name: standardnotes-web
    env_file: pathtofile/.env
    restart: unless-stopped
    ports:
      - "${PORT}:3001"
    volumes:
      - pathtovolume/:/app
    networks:
      - default
```
And with this env-File:
RAILS_ENV=development
PORT=3001
WEB_CONCURRENCY=0
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
SECRET_KEY_BASE= same secret key i generated for the sync-server
APP_HOST=http://localhost:3001

EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
SF_DEFAULT_SERVER= tried ip of my docker sync-server and the domain with port

# Datadog
DATADOG_ENABLED=false

The sync-server with docker hub image runs flawlessly.
If you need more information do not hesitate to contact me. I'm thankful for any help ;-)

I am happy to hear from you.

**Comment by karolsojko** [comment]
```
starting container process caused "exec: \"./docker/entrypoint.sh\": stat ./docker/entrypoint.sh: no such file or directory": unknown
```

This should be fixed by: https://github.com/standardnotes/web/commit/6b4e9e317f13626da1c92edf5aadb9a8da98e7d8
 (applied both in `develop` and `master` branch)

As for these messages:
```
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/notifications/fanout.rb:19: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead,
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/stack.rb:35: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call,
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:109: warning: The called method `initialize' is defined here,
/usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
```
Those are just warnings, not errors and don't affect the application. The issue is already known and requires a Rails version upgrade: https://github.com/standardnotes/web/issues/438

As for the docker-compose setup, if you are mounting volumes to the container please use the `start-local` command (regardless if you use the `latest` or `stable` version): https://github.com/standardnotes/web/blob/develop/docker-compose.yml#L6

@MakiG0 please let us know if this fixes the issue

**Comment by MakiG0** [comment]
@karolsojko thanks for updating the docker image and response.
I tested the latest stable image with the command `start-local` and the error is still there:
`OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"./docker/entrypoint.sh\": stat ./docker/entrypoint.sh: no such file or directory": unknown
`
 i used this docker-compose:
```
version: "3.6"
services:
  standardnotes-web:
    image: standardnotes/web:stable
    command: start-local
    container_name: standardnotes-web
    env_file: pathtofile/.env
    restart: unless-stopped
    ports:
      - "${PORT}:3001"
    volumes:
      - pathtovolume/:/app
    networks:
      - default
```

what am i doing wrong?!

**Comment by karolsojko** [comment]
I'm guessing it's this part: 
```
    volumes:
      - pathtovolume/:/app
```

if you want to use docker-compose (which is mainly for development/contributing purposes) instead of just `docker run ...` with the official image, you have to mount the full application source code under `/app` 

So this is the file I've created under the root folder of the repo and it works:

```
version: "3.6"
services:
  standardnotes-web:
    image: standardnotes/web:stable
    command: start-local
    container_name: standardnotes-web
    env_file: .env
    restart: unless-stopped
    ports:
      - "${PORT}:3001"
    volumes:
      - .:/app
    networks:
      - default
```

Nevertheless we already have a docker-compose setup in the repo: https://github.com/standardnotes/web#contributing

But we highly recommend using Docker if you're not developing the application locally: https://github.com/standardnotes/web#standalone-instance

**Comment by MakiG0** [comment]
i changed my docker-compose and use it exactly you mentioned above. I downloaded the repo in the `/app` folder.
I also tried using docker and this command `docker run -d -p 3001:3001 --env-file=your-env-file standardnotes/web:stable`.

The result is as before: `Starting server` message in the log and nothing happend.

Is it possible that my env-file is not right? Can you tell me which values I have to write in which line?

**Comment by karolsojko** [comment]
`Starting server...` is the last message of the startup script ... I think you can wait a couple of seconds after that and access the server on appropriate port.

**Comment by MakiG0** [comment]
i have waited several hours. However, when I open the web service I do not get a page displayed. Do you have any other tips or do you need more information?

**Comment by GaetanLepage** [comment]
I have exactly the same problem.
I tried running the container via docker-compose and also using the given `docker run` command.
Everything "looks" fine but a curl localhost:3001 gives `curl: (56) Recv failure: Connection reset by peer`.

Does someone has an idea ?

**Comment by mhellmeier** [comment]
Got the same problem with docker-compose and found a fix.

> As for the docker-compose setup, if you are mounting volumes to the container please use the `start-local` command (regardless if you use the `latest` or `stable` version): https://github.com/standardnotes/web/blob/develop/docker-compose.yml#L6

This doesn't work for me when using volumes. Despite setting the `start-local` command, it doesn't get the files. My solution:

**Version 1**
Don't use volumes _(not recommend)_

**Version 2**
1. Create a `docker-compose.yml` file, use the `image: standardnotes/web:stable` and mount the volume, for example
```
volumes:
  - ./web:/app
```
2. Clone the repo in your local environment with `git clone https://github.com/standardnotes/web.git`
3. Go into the folder (`cd web`) and switch to master branch (`git checkout master`)
4. Start your service with `docker-compose up -d`



> if you want to use docker-compose (which is mainly for development/contributing purposes) instead of just `docker run ...` with the official image [...]

Why not? Compose is fine for production, for example by using the Docker Hub image instead of building local. The docker documentation has it's one page for [compose in production](https://docs.docker.com/compose/production/).

**Comment by karolsojko** [comment]
As per [Docker docs](https://docs.docker.com/compose/#common-use-cases):

```
Compose has traditionally been focused on development and testing workflows, but with each release we’re making progress on more production-oriented features.
```

So it depends on what you mean by `production` if it's a single host machine with all relationships defined then I guess you're fine with running Docker compose there. When it's a dynamic scalable solution as it is in our case then it's not quite suitable.

**Comment by karolsojko** [comment]
I'm closing the issue as this seems to be resolved. Please feel free to reopen if needed.
